### PR TITLE
use clorox instead of chalk?

### PR DESCRIPTION
**Pull request by Rich-Harris**
Hey — wonder what you'd think about using [clorox](https://github.com/jorgebucaran/clorox) here instead of chalk? It does exactly the same thing (at least as far as this package is concerned) but much more simply:

* http://npm.anvaka.com/#/view/2d/clorox
* http://npm.anvaka.com/#/view/2d/chalk
* https://bundlephobia.com/result?p=clorox@1.0.3
* https://bundlephobia.com/result?p=chalk@2.3.2

No problem if you'd rather keep it aligned with CRA.

(For context, I'm trying to reduce the install time/footprint of Sapper)

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, thanks!!

Yeah, I would have used Clorox from the beginning but webpack is already using chalk iirc. I'll address this in a few at my desk. 🎉

**Comment by lukeed** [comment]
Was more than a few minutes because 1) Saturday and 2) I spent way too much time in that anvaka tool 🙈

**Comment by lukeed** [comment]
Out in `1.0.2` -- thanks @Rich-Harris!

**Comment by Rich-Harris** [comment]
woot, thanks!

**Comment by snuggs** [comment]
Boss move @Rich-Harris ;-) Thanks @lukeed

**Comment by lukeed** [comment]
Lol gone are the days where chalk had zero deps

**Comment by snuggs** [comment]
@lukeed #ISeeWhatYouDidThere 😄

**Pull request merged**
